
"""Manager for enhanced smart-grid appliance models."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from smart_grid_rl.appliance_models import (
    ApplianceContext,
    ApplianceModel,
)


@dataclass
class ApplianceStepResult:
    """Results generated by appliances during one environment step."""

    load_kw: float
    wasted_kwh: float
    comfort_penalty: float
    observations: list[float]


class ApplianceManager:
    """Controls and evaluates enhanced appliance models."""

    def __init__(
        self,
        appliances: Sequence[ApplianceModel],
        dt_hours: float = 0.25,
    ) -> None:

        if dt_hours <= 0:
            raise ValueError("dt_hours must be positive")

        self.appliances = list(appliances)
        self.dt_hours = dt_hours

        # Store the last action and accumulated energy for
        # observation generation in the environment.
        for appliance in self.appliances:
            appliance.last_action = 0
            appliance.total_energy_kwh = 0.0

    @property
    def action_sizes(self) -> list[int]:
        """Return the number of legal actions for each appliance."""

        return [
            appliance.num_actions()
            for appliance in self.appliances
        ]

    def reset(self) -> None:
        """Reset every enhanced appliance."""

        for appliance in self.appliances:
            appliance.reset()

            # These attributes are used by the enhanced state encoder.
            appliance.last_action = 0
            appliance.total_energy_kwh = 0.0

    def apply_actions(
        self,
        actions: Sequence[int],
        ctx: ApplianceContext,
    ) -> None:
        """Apply one action to every appliance."""

        if len(actions) != len(self.appliances):
            raise ValueError(
                f"Expected {len(self.appliances)} appliance actions, "
                f"got {len(actions)}"
            )

        for appliance, action in zip(self.appliances, actions):

            action = int(action)

            if action < 0 or action >= appliance.num_actions():
                raise ValueError(
                    f"Invalid action {action} for {appliance.name}. "
                    f"Expected a value between "
                    f"0 and {appliance.num_actions() - 1}."
                )

            appliance.apply_action(action, ctx)

            # Save the action for state representation.
            appliance.last_action = action

    def step(
        self,
        ctx: ApplianceContext,
    ) -> ApplianceStepResult:
        """Advance all appliances by one environment step."""

        load_kw = 0.0
        wasted_kwh = 0.0
        comfort_penalty = 0.0
        observations: list[float] = []

        for appliance in self.appliances:

            # tick() returns power in kW.
            appliance_power_kw = float(
                appliance.tick(ctx)
            )

            load_kw += appliance_power_kw

            # Accumulate energy consumed during this step.
            energy_kwh = (
                appliance_power_kw * self.dt_hours
            )

            appliance.total_energy_kwh = (
                getattr(
                    appliance,
                    "total_energy_kwh",
                    0.0,
                )
                + energy_kwh
            )

            # Calculate wasted energy.
            wasted_kwh += float(
                appliance.wasted_kwh(
                    ctx,
                    self.dt_hours,
                )
            )

            # Calculate comfort or scheduling penalty.
            comfort_penalty += float(
                appliance.comfort_penalty(ctx)
            )

            # Collect appliance observations.
            appliance_observation = appliance.obs(ctx)

            observations.extend(
                float(value)
                for value in appliance_observation
            )

        return ApplianceStepResult(
            load_kw=float(load_kw),
            wasted_kwh=float(wasted_kwh),
            comfort_penalty=float(comfort_penalty),
            observations=observations,
        )